### ISSUE TITLE
1.17.1 Command Error

### ISSUE THREAD

**Issue by knniDE** [SentixDev/Pl3xMap-Marker#1]
**Every time a command is executed, the following error appears in the console:**
```
[16:03:05 INFO]: KNNI issued server command: /pl3xmarker help
[16:03:05 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pl3xmarker' in plugin Pl3xMap-Marker v1.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-356]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-356]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-356]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2262) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-356]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1423) ~[patched_1.17.1.jar:git-Paper-356]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-356]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1401) ~[patched_1.17.1.jar:git-Paper-356]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1394) ~[patched_1.17.1.jar:git-Paper-356]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1372) ~[patched_1.17.1.jar:git-Paper-356]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Paper-356]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-356]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/kyori/adventure/text/minimessage/MiniMessage
        at god.sentix.pl3xmapmarker.Chat.send(Chat.kt:11) ~[Pl3xMap-Marker.jar:?]
        at god.sentix.pl3xmapmarker.commands.MarkerCMD.sendHelpMessage(MarkerCMD.kt:146) ~[Pl3xMap-Marker.jar:?]
        at god.sentix.pl3xmapmarker.commands.MarkerCMD.onCommand(MarkerCMD.kt:123) ~[Pl3xMap-Marker.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-356]
        ... 21 more
```
_The plugin does not work in this state._

**Version information**
```
> version Pl3xMap-Marker
[16:00:42 INFO]: Pl3xMap-Marker version 1.5
[16:00:42 INFO]: Simple plugin to add markers on pl3xmap
[16:00:42 INFO]: Author: Sentix
> version Pl3xMap
[16:02:07 INFO]: Pl3xMap version 1.0.0-BETA-162
[16:02:07 INFO]: Minimalistic and lightweight world map viewer for Paper servers
[16:02:07 INFO]: Website: https://github.com/pl3xgaming/Pl3xMap/
[16:02:07 INFO]: Authors: BillyGalbreath and jmp
> version
[16:02:15 INFO]: Checking version, please wait...
[16:02:15 INFO]: This server is running Paper version git-Paper-356 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 744dd8c)
```

**Comment by SentixDev** [comment]
Damn, im sorry. It is fixed in version 1.5.1. https://www.spigotmc.org/resources/pl3xmap-marker.97262/
