### ISSUE TITLE
Error on startup - 1.18.2

### ISSUE THREAD

**Issue by mpab1410** [SentixDev/Pl3xMap-Marker#11]
```
[06:05:36 INFO]: [Pl3xMap-Marker] Enabling Pl3xMap-Marker v4.1
[06:05:36 ERROR]: Error occurred while enabling Pl3xMap-Marker v4.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage net.kyori.adventure.text.minimessage.MiniMessage.get()'
        at god.sentix.pl3xmarker.Chat.send(Chat.kt:9) ~[Pl3xMap-Marker-4.1.jar:?]
        at god.sentix.pl3xmarker.Main.onEnable(Main.kt:25) ~[Pl3xMap-Marker-4.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-246]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-246]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1165) ~[paper-1.18.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-246]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[06:05:36 INFO]: [Pl3xMap-Marker] Disabling Pl3xMap-Marker v4.1
[06:05:36 ERROR]: Error occurred while disabling Pl3xMap-Marker v4.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at god.sentix.pl3xmarker.service.MarkerService$API.unregister(MarkerService.kt:134) ~[Pl3xMap-Marker-4.1.jar:?]
        at god.sentix.pl3xmarker.Main.onDisable(Main.kt:52) ~[Pl3xMap-Marker-4.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-246]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-246]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1165) ~[paper-1.18.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-246]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property configuration has not been initialized
        at god.sentix.pl3xmarker.Main$Companion.getConfiguration(Main.kt:18) ~[Pl3xMap-Marker-4.1.jar:?]
        at god.sentix.pl3xmarker.storage.StaticStorage.<clinit>(StaticStorage.kt:13) ~[Pl3xMap-Marker-4.1.jar:?]
        ... 15 more
```

I know 1.18.2 Paper did add a new version of MiniMessage/Adventure, so I'm assuming that would be the culprit but if you can take a look that would be greatly appreciated!

**Comment by SentixDev** [comment]
https://github.com/SentixDev/squaremarker
